version: '3.9'

services:
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    depends_on:
      - mysql
volumes:
  data-db:
  
