version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      AWS_S3_ENDPOINT: http://s3:9000
      S3_BUCKET: my-first-bucket
      AWS_ACCESS_KEY_ID: benighilbenighil
      AWS_SECRET_ACCESS_KEY: marsmarsmars
  s3:
    image: bitnami/minio:2021.12.29
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: 'my-first-bucket:public'
      BITNAMI_DEBUG: true
    