version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT} 
      S3_BUCKET: ${S3_BUCKET} 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} 
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY} 
  s3:
    image: bitnami/minio:2021.12.29
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: 'my-first-bucket:public'
      BITNAMI_DEBUG: true
    